name: Build and Deploy

on:
  push:
    branches:
      - main  # Reemplazar por tu rama por defecto si no es "main"

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18.8.0
          cache: 'npm'
          cache-dependency-path: esi-app/package-lock.json

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
        working-directory: esi-app

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: esi-app/dist  # Reemplazar si tu carpeta de build es distinta
